import asyncio
from typing import List
from datetime import datetime
from langchain_google_genai import ChatGoogleGenerativeAI
import os
from langchain_core.prompts import ChatPromptTemplate
from pydantic import BaseModel, Field

from agents.scoring_agent import CandidateScore


class HiringReport(BaseModel):
    job_title: str = Field(description="The job position being filled")
    report_date: str = Field(description="Date the report was generated")
    total_candidates: int = Field(description="Total number of candidates evaluated")
    executive_summary: str = Field(description="3-4 sentences summarizing the hiring pool quality and recommendation")
    top_candidate: str = Field(description="Name of the most qualified candidate")
    top_candidate_reason: str = Field(description="2-3 sentences explaining why this candidate stands out")
    recommended_interviews: List[str] = Field(description="Names to proceed with, ordered by priority")
    not_recommended: List[str] = Field(description="Names not suitable for this role")
    hiring_insights: str = Field(description="2-3 patterns or observations across all candidates")
    suggested_action: str = Field(description="One clear, specific next step for the HR team")


async def generate_hiring_report(
    job_description: str,
    ranked_candidates: List[CandidateScore]
) -> HiringReport:
    llm = ChatGoogleGenerativeAI(
    model="gemini-2.0-flash", # نسخة pro قوية في صياغة التقارير الطويلة وضمان سلامة الـ JSON المتوقع للـ UI
    google_api_key=os.getenv("GEMINI_API_KEY"),
    temperature=0.2
)

    candidates_summary = "\n\n".join([
        f"""Candidate: {c.candidate_name}
Overall Score: {c.overall_score:.1f}/10
Recommendation: {c.recommendation}
Technical: {c.technical_score:.1f} | Job Fit: {c.job_fit_score:.1f} | Communication: {c.communication_score:.1f}
Strengths: {', '.join(c.strengths)}
Gaps: {', '.join(c.gaps)}
Reasoning: {c.reasoning}"""
        for c in ranked_candidates
    ])

    prompt = ChatPromptTemplate.from_messages([
        (
            "system",
            """You are a senior HR consultant writing an executive hiring report.
            
            This report is READ BY HUMANS who make hiring decisions.
            
            Writing rules:
            - Lead with the most important insight
            - Translate scores into decisions, don't just repeat numbers
            - Be direct: HR needs to know WHO to call first and WHY
            - Write professionally but clearly — no jargon
            - Suggested action must be specific and actionable
            """
        ),
        (
            "human",
            """
            ── POSITION ─────────────────────────────────────
            {job_description}
            
            ── EVALUATED CANDIDATES (ranked by score) ───────
            {candidates_summary}
            
            ── REPORT DATE ──────────────────────────────────
            {report_date}
            
            Generate the executive hiring report:
            """
        )
    ])

    chain = prompt | llm.with_structured_output(HiringReport)

    return await chain.ainvoke({
        "job_description": job_description,
        "candidates_summary": candidates_summary,
        "report_date": datetime.now().strftime("%B %d, %Y")
    })


def format_report(report: HiringReport) -> str:
    recommended = "\n".join([
        f"   {i+1}. {name}"
        for i, name in enumerate(report.recommended_interviews)
    ])

    not_recommended = "\n".join([
        f"   • {name}"
        for name in report.not_recommended
    ]) or "   None"

    return f"""
╔══════════════════════════════════════════════════════╗
║              AI HIRING SYSTEM REPORT                 ║
╠══════════════════════════════════════════════════════╣
║  Position   : {report.job_title:<38}║
║  Date       : {report.report_date:<38}║
║  Candidates : {str(report.total_candidates) + ' evaluated':<38}║
╚══════════════════════════════════════════════════════╝

📋 EXECUTIVE SUMMARY
{report.executive_summary}

🏆 TOP CANDIDATE — {report.top_candidate}
{report.top_candidate_reason}

✅ RECOMMENDED FOR INTERVIEW (priority order)
{recommended}

❌ NOT RECOMMENDED
{not_recommended}

💡 HIRING INSIGHTS
{report.hiring_insights}

🎯 NEXT ACTION
{report.suggested_action}

{'─'*54}
Generated by AI Hiring System | {report.report_date}
"""


if __name__ == "__main__":
    sample_scores = [
        CandidateScore(
            candidate_name="Sara Ahmed",
            technical_score=8.5,
            experience_score=7.0,
            communication_score=8.0,
            job_fit_score=8.0,
            overall_score=8.2,
            strengths=["RAG expertise", "Async Python", "API design"],
            gaps=["No LangGraph experience", "Limited production scale"],
            recommendation="Strong Yes",
            reasoning="Demonstrated strong practical knowledge. Answers showed real understanding of production AI challenges."
        ),
        CandidateScore(
            candidate_name="Ahmed Hassan",
            technical_score=5.0,
            experience_score=6.0,
            communication_score=4.0,
            job_fit_score=3.5,
            overall_score=4.1,
            strengths=["Traditional ML", "Docker", "5 years experience"],
            gaps=["No LLM knowledge", "No RAG experience", "Weak interview performance"],
            recommendation="No",
            reasoning="Despite seniority, lacks all core LLM requirements. Interview confirmed no practical AI agent experience."
        )
    ]

    job_desc = "Senior AI Engineer — LangGraph, LLMs, FastAPI, Production AI Systems"

    report = asyncio.run(generate_hiring_report(job_desc, sample_scores))
    print(format_report(report))